

// All user-facing strings are translated to Korean.
import { StatusEffectType, GameConfig as AppGameConfig, SkillDefinition, StatModifier, PlayerStats, StatusEffectDefinition as AppStatusEffectDefinition, ItemType, PermanentUpgradeConfigItem, PermanentStatsLevels, Rarity, ItemEnhancementConfig } from './types.ts'; 

export const RARITY_COLORS: Record<string, string> = {
  ['일반']: 'text-gray-300',
  ['고급']: 'text-sky-400', 
  ['희귀']: 'text-yellow-400',
  ['영웅']: 'text-purple-400',
  ['전설']: 'text-orange-500',
};

const DEFAULT_ITEM_ENHANCEMENT_CONFIG: ItemEnhancementConfig = {
  maxLevelByRarity: {
    [Rarity.COMMON]: 3,
    [Rarity.UNCOMMON]: 5,
    [Rarity.RARE]: 7,
    [Rarity.EPIC]: 9,
    [Rarity.LEGENDARY]: 10,
  },
  baseGoldCost: 20,
  goldCostIncreaseFactorPerLevel: 1.5, // Cost = base * (factor ^ currentLevel)
  baseStoneCost: 1,
  stoneCostIncreaseFactorPerLevel: 1.3, // Cost = base * (factor ^ currentLevel)
  itemLevelMultiplier: 0.1, // Cost also multiplied by (1 + itemEffectiveLevel * this_multiplier)
  bonusPerLevel: 0.05, // 5% bonus to modifier values per enhancement level
};

export const GAME_CONFIG: AppGameConfig = {
  initialPlayerRunStats: { // Renamed from initialPlayerStats
    hp: 180, 
    maxHp: 180, 
    attack: 16, 
    defense: 10, 
    critChance: 0.05, 
    critDamage: 1.5, 
    healthRegen: 2.2, 
    gold: 100, // Starting gold for the very first run, or if not carried over
    attackSpeed: 1.0, 
  },
  playerLevelUpStatPoints: 5,
  baseExpToLevel: 70, 
  expScalingFactor: 1.4, 
  monsterSpawnIntervalMs: 1250, 
  battleTickIntervalMs: 500,
  maxMonstersOnScreen: 80,
  healthRegenIntervalMs: 1000, 
  playerBaseStatusEffectChance: { 
    type: StatusEffectType.POISON,
    chance: 0.15, 
    potency: 2,   
    duration: 3,  
  },
  BOSS_WAVE_INTERVAL: 10,
  BOSS_LOOT_MIN_RARITY_INDEX: 1, 
  PLAYER_MOVEMENT_SPEED: 2, 
  MONSTER_MOVEMENT_SPEED: 1.5, 
  ENGAGEMENT_RANGE: 1.5, 
  AGGRO_RANGE: 10, 
  MAP_BOUNDS: { minX: -12.5, maxX: 12.5, minZ: -12.5, maxZ: 12.5 }, 
  PLAYER_Y_POSITION: 0.4, 
  MONSTER_BASE_Y_SCALE_FACTOR: 0.5, 
  MOVEMENT_TARGET_UPDATE_COOLDOWN_TICKS: 3, 
  QUAKE_STOMP_RADIUS: 3,
  LUCKY_STREAK_DURATION_TICKS: 30, 
  LUCKY_STREAK_WINDOW_TICKS: 5,
  MIN_MONSTERS_PER_NON_BOSS_WAVE: 3, 
  MONSTERS_PER_WAVE_INCREMENT: 1, 
  INITIAL_WAVE_MONSTER_COUNT_OVERRIDES: { 1: 3, 2: 4, 3: 5, 4: 6, 5: 7 },
  ENHANCEMENT_STONE_DROP_CHANCE: 0.15, // 15% chance to drop stones
  ENHANCEMENT_STONE_DROP_AMOUNT: [1, 3], // Drops 1 to 3 stones
  ITEM_ENHANCEMENT_CONFIG: DEFAULT_ITEM_ENHANCEMENT_CONFIG,
};

export const PERMANENT_UPGRADES_SETTINGS: PermanentUpgradeConfigItem[] = [
  {
    key: 'maxHp',
    name: '영구 최대 체력',
    description: (bonusPerLevel, currentLevel, nextBonus) => `최대 체력이 영구적으로 ${nextBonus.toFixed(0)} 증가합니다. (현재: +${(currentLevel * bonusPerLevel).toFixed(0)})`,
    bonusPerLevel: 10,
    baseCost: 5,
    costIncreasePerLevel: 3,
    maxUpgradeLevel: 50,
    icon: '❤️',
  },
  {
    key: 'attack',
    name: '영구 공격력',
    description: (bonusPerLevel, currentLevel, nextBonus) => `공격력이 영구적으로 ${nextBonus.toFixed(0)} 증가합니다. (현재: +${(currentLevel * bonusPerLevel).toFixed(0)})`, // Changed toFixed(0) for attack
    bonusPerLevel: 1,
    baseCost: 8,
    costIncreasePerLevel: 4,
    maxUpgradeLevel: 50,
    icon: '⚔️',
  },
  {
    key: 'defense',
    name: '영구 방어력',
    description: (bonusPerLevel, currentLevel, nextBonus) => `방어력이 영구적으로 ${nextBonus.toFixed(0)} 증가합니다. (현재: +${(currentLevel * bonusPerLevel).toFixed(0)})`, // Changed toFixed(0) for defense
    bonusPerLevel: 0.5,
    baseCost: 6,
    costIncreasePerLevel: 3,
    maxUpgradeLevel: 50,
    icon: '🛡️',
  },
  {
    key: 'healthRegen',
    name: '영구 체력 재생',
    description: (bonusPerLevel, currentLevel, nextBonus) => `초당 체력 재생량이 영구적으로 ${nextBonus.toFixed(2)} 증가합니다. (현재: +${(currentLevel * bonusPerLevel).toFixed(2)})`,
    bonusPerLevel: 0.1,
    baseCost: 10,
    costIncreasePerLevel: 5,
    maxUpgradeLevel: 30,
    icon: '✨',
  },
];

export const BOSS_ESSENCE_DROP = 10;
export const WAVE_CLEAR_ESSENCE_MULTIPLIER = 0.2; // Essence = waveNumber * this value on game over.


export const STATUS_EFFECT_DEFINITIONS: Record<StatusEffectType, AppStatusEffectDefinition> = {
  [StatusEffectType.POISON]: {
    name: '독',
    icon: '🧪',
    defaultPotency: 1, 
    defaultDuration: 3, 
    description: (potency, duration) => `매 턴마다 ${potency}의 독 피해를 ${duration}턴 동안 입힙니다.`,
    isBuff: false,
  },
  [StatusEffectType.STUN]: {
    name: '기절',
    icon: '💫',
    defaultPotency: 0, 
    defaultDuration: 1, 
    description: (duration) => `${duration}턴 동안 행동 불가 상태가 됩니다.`,
    isBuff: false,
  },
  [StatusEffectType.DEFENSE_DOWN]: {
    name: '방어력 감소',
    icon: '🛡️↘️',
    defaultPotency: 0.1, 
    defaultDuration: 3, 
    description: (potency, duration) => `방어력이 ${Math.round(potency * 100)}% 만큼 ${duration}턴 동안 감소합니다.`,
    isBuff: false,
  },
  [StatusEffectType.ATTACK_SPEED_BUFF]: {
    name: '공격 속도 증가',
    icon: '💨⚔️',
    defaultPotency: 0.1, 
    defaultDuration: 3, 
    description: (potency, duration) => `공격 속도가 ${Math.round(potency * 100)}% 만큼 ${duration}턴 동안 증가합니다.`,
    isBuff: true,
  },
  [StatusEffectType.MOVEMENT_SPEED_BUFF]: {
    name: '이동 속도 증가',
    icon: '🏃💨',
    defaultPotency: 0.1, 
    defaultDuration: 3, 
    description: (potency, duration) => `이동 속도가 ${Math.round(potency * 100)}% 만큼 ${duration}턴 동안 증가합니다.`,
    isBuff: true,
  },
  [StatusEffectType.VULNERABILITY]: {
    name: '취약',
    icon: '🎯💔',
    defaultPotency: 0.1, 
    defaultDuration: 5, 
    description: (potency, duration) => `받는 모든 피해가 ${Math.round(potency * 100)}% 만큼 ${duration}턴 동안 증가합니다.`,
    isBuff: false,
  },
  [StatusEffectType.SLOW]: {
    name: '둔화',
    icon: '🐌',
    defaultPotency: 0.2, 
    defaultDuration: 3, 
    description: (potency, duration) => `이동 속도가 ${Math.round(potency * 100)}% 만큼 ${duration}턴 동안 감소합니다.`,
    isBuff: false,
  },
  [StatusEffectType.BLEED]: {
    name: '출혈',
    icon: '🩸',
    defaultPotency: 2, 
    defaultDuration: 3, 
    description: (potency, duration) => `매 턴마다 ${potency}의 출혈 피해를 ${duration}턴 동안 입힙니다.`,
    isBuff: false,
  },
  [StatusEffectType.ATTACK_BUFF]: {
    name: '공격력 증가',
    icon: '💪✨',
    defaultPotency: 0.1, 
    defaultDuration: 3, 
    description: (potency, duration) => `공격력이 ${Math.round(potency * 100)}% 만큼 ${duration}턴 동안 증가합니다.`,
    isBuff: true,
  },
  [StatusEffectType.ALL_STATS_BUFF]: {
    name: '모든 능력치 증가',
    icon: '🌟💪',
    defaultPotency: 0.05, 
    defaultDuration: 5, 
    description: (potency, duration) => `주요 능력치(공격력, 방어력, 최대 체력)가 ${Math.round(potency * 100)}% 만큼 ${duration}턴 동안 증가합니다.`,
    isBuff: true,
  },
  [StatusEffectType.GOLD_FIND_BUFF]: {
    name: '골드 발견량 증가',
    icon: '💰✨',
    defaultPotency: 0.5, 
    defaultDuration: 30, 
    description: (potency, duration) => `골드 발견량이 ${Math.round(potency * 100)}% 만큼 ${duration}턴 동안 증가합니다.`,
    isBuff: true,
  },
  [StatusEffectType.MASTER_TACTICIAN_BUFF]: {
    name: '전술의 대가 활성',
    icon: '🗺️⏱️',
    defaultPotency: 0, 
    defaultDuration: 5, 
    description: (duration) => `전투 시작 후 ${duration}턴 동안 치명타 확률 및 피해량 증가.`,
    isBuff: true,
  }
};

export const MONSTER_DEFINITIONS = [
  // 일반 몬스터 스탯 조정 (HP/Atk/보상 ~1/4, Def ~1/2, DoT potency ~1/2)
  { id: 'goblin', name: '고블린 그런트', baseHp: Math.max(1, Math.round(24/4)), baseAttack: Math.max(1, Math.round(4/4)), baseDefense: Math.max(1, Math.round(2/2)), goldDrop: [Math.max(1, Math.round(1/4)), Math.max(1, Math.round(5/4))] as [number,number], xpDrop: Math.max(1, Math.round(12/4)), color: 'bg-green-700', sizeClass: 'w-10 h-10' },
  { id: 'skeleton', name: '해골 전사', baseHp: Math.max(1, Math.round(40/4)), baseAttack: Math.max(1, Math.round(6/4)), baseDefense: Math.max(1, Math.round(3/2)), goldDrop: [Math.max(1, Math.round(3/4)), Math.max(1, Math.round(8/4))] as [number,number], xpDrop: Math.max(1, Math.round(18/4)), color: 'bg-gray-500', sizeClass: 'w-12 h-12' },
  { id: 'orc', name: '오크 브루트', baseHp: Math.max(1, Math.round(80/4)), baseAttack: Math.max(1, Math.round(10/4)), baseDefense: Math.max(1, Math.round(5/2)), goldDrop: [Math.max(1, Math.round(5/4)), Math.max(1, Math.round(15/4))] as [number,number], xpDrop: Math.max(1, Math.round(36/4)), color: 'bg-red-700', sizeClass: 'w-16 h-16' },
  { 
    id: 'dark_mage', 
    name: '어둠의 마법사', 
    baseHp: Math.max(1, Math.round(56/4)), 
    baseAttack: Math.max(1, Math.round(12/4)), 
    baseDefense: Math.max(1, Math.round(2/2)), 
    goldDrop: [Math.max(1, Math.round(10/4)), Math.max(1, Math.round(25/4))] as [number,number], 
    xpDrop: Math.max(1, Math.round(48/4)), 
    color: 'bg-purple-700', 
    sizeClass: 'w-12 h-16',
    appliesEffect: { type: StatusEffectType.STUN, chance: 0.25, potency: 0, duration: 1 } // Stun potency/duration not changed for now
  },
  { id: 'demon_imp', name: '악마 임프', baseHp: Math.max(1, Math.round(32/4)), baseAttack: Math.max(1, Math.round(8/4)), baseDefense: Math.max(0, Math.round(1/2)), goldDrop: [Math.max(1, Math.round(2/4)), Math.max(1, Math.round(7/4))] as [number,number], xpDrop: Math.max(1, Math.round(15/4)), color: 'bg-red-900', sizeClass: 'w-8 h-8' },
  
  // 보스 몬스터 (스탯 변경 없음)
  { 
    id: 'goblin_tyrant', 
    name: '고블린 폭군', 
    isBoss: true,
    baseHp: 240, 
    baseAttack: 20, 
    baseDefense: 10, 
    goldDrop: [50, 100] as [number,number], 
    xpDrop: 180, 
    color: 'bg-emerald-700', 
    sizeClass: 'w-20 h-20'
  },

  // 신규 일반 몬스터 스탯 조정
  { 
    id: 'venom_basilisk', name: '맹독 바실리스크', baseHp: Math.max(1, Math.round(60/4)), baseAttack: Math.max(1, Math.round(7/4)), baseDefense: Math.max(1, Math.round(4/2)), goldDrop: [Math.max(1, Math.round(8/4)), Math.max(1, Math.round(18/4))] as [number,number], xpDrop: Math.max(1, Math.round(25/4)), 
    color: 'bg-lime-600', sizeClass: 'w-14 h-10', 
    appliesEffect: { type: StatusEffectType.POISON, chance: 0.3, potency: Math.max(1, Math.round(3/2)), duration: 4 }
  },
  { 
    id: 'frost_archer', name: '서리 해골 궁수', baseHp: Math.max(1, Math.round(35/4)), baseAttack: Math.max(1, Math.round(9/4)), baseDefense: Math.max(0, Math.round(1/2)), goldDrop: [Math.max(1, Math.round(7/4)), Math.max(1, Math.round(15/4))] as [number,number], xpDrop: Math.max(1, Math.round(22/4)), 
    color: 'bg-cyan-600', sizeClass: 'w-12 h-12', 
    appliesEffect: { type: StatusEffectType.SLOW, chance: 0.2, potency: 0.3, duration: 2 } // Slow potency not changed for now
  },
  { id: 'granite_golem', name: '화강암 골렘', baseHp: Math.max(1, Math.round(120/4)), baseAttack: Math.max(1, Math.round(8/4)), baseDefense: Math.max(1, Math.round(8/2)), goldDrop: [Math.max(1, Math.round(15/4)), Math.max(1, Math.round(30/4))] as [number,number], xpDrop: Math.max(1, Math.round(50/4)), color: 'bg-stone-500', sizeClass: 'w-18 h-18' },
  { id: 'shadow_stalker', name: '그림자 추적자', baseHp: Math.max(1, Math.round(45/4)), baseAttack: Math.max(1, Math.round(11/4)), baseDefense: Math.max(1, Math.round(2/2)), goldDrop: [Math.max(1, Math.round(12/4)), Math.max(1, Math.round(28/4))] as [number,number], xpDrop: Math.max(1, Math.round(40/4)), color: 'bg-indigo-700', sizeClass: 'w-10 h-14' },
  { 
    id: 'plague_rat_swarm', name: '역병 쥐떼', baseHp: Math.max(1, Math.round(20/4)), baseAttack: Math.max(1, Math.round(5/4)), baseDefense: Math.max(0, Math.round(0/2)), goldDrop: [Math.max(1, Math.round(1/4)), Math.max(1, Math.round(4/4))] as [number,number], xpDrop: Math.max(1, Math.round(10/4)), 
    color: 'bg-amber-700', sizeClass: 'w-10 h-6',
    appliesEffect: { type: StatusEffectType.DEFENSE_DOWN, chance: 0.15, potency: 0.05, duration: 3 } // Debuff potency not changed for now
  },
  { id: 'swamp_horror', name: '늪지 괴물', baseHp: Math.max(1, Math.round(75/4)), baseAttack: Math.max(1, Math.round(9/4)), baseDefense: Math.max(1, Math.round(5/2)), goldDrop: [Math.max(1, Math.round(10/4)), Math.max(1, Math.round(22/4))] as [number,number], xpDrop: Math.max(1, Math.round(33/4)), color: 'bg-teal-700', sizeClass: 'w-15 h-15' },
  { 
    id: 'hellhound', name: '지옥 사냥개', baseHp: Math.max(1, Math.round(50/4)), baseAttack: Math.max(1, Math.round(13/4)), baseDefense: Math.max(1, Math.round(3/2)), goldDrop: [Math.max(1, Math.round(14/4)), Math.max(1, Math.round(26/4))] as [number,number], xpDrop: Math.max(1, Math.round(42/4)), 
    color: 'bg-orange-600', sizeClass: 'w-14 h-10',
    appliesEffect: { type: StatusEffectType.BLEED, chance: 0.25, potency: Math.max(1, Math.round(4/2)), duration: 3 }
  },
  { id: 'ancient_guardian', name: '고대 수호자', baseHp: Math.max(1, Math.round(150/4)), baseAttack: Math.max(1, Math.round(12/4)), baseDefense: Math.max(1, Math.round(12/2)), goldDrop: [Math.max(1, Math.round(30/4)), Math.max(1, Math.round(60/4))] as [number,number], xpDrop: Math.max(1, Math.round(70/4)), color: 'bg-sky-700', sizeClass: 'w-20 h-20' },
  { 
    id: 'cave_spider', name: '동굴 거미', baseHp: Math.max(1, Math.round(30/4)), baseAttack: Math.max(1, Math.round(7/4)), baseDefense: Math.max(0, Math.round(1/2)), goldDrop: [Math.max(1, Math.round(4/4)), Math.max(1, Math.round(10/4))] as [number,number], xpDrop: Math.max(1, Math.round(17/4)), 
    color: 'bg-neutral-600', sizeClass: 'w-10 h-10',
    appliesEffect: { type: StatusEffectType.SLOW, chance: 0.2, potency: 0.2, duration: 3 } // Slow potency not changed
  },
  { id: 'berserker_dwarf', name: '광포한 드워프', baseHp: Math.max(1, Math.round(90/4)), baseAttack: Math.max(1, Math.round(14/4)), baseDefense: Math.max(1, Math.round(6/2)), goldDrop: [Math.max(1, Math.round(18/4)), Math.max(1, Math.round(35/4))] as [number,number], xpDrop: Math.max(1, Math.round(55/4)), color: 'bg-rose-700', sizeClass: 'w-12 h-14' },
  { id: 'phantom_soldier', name: '유령 병사', baseHp: Math.max(1, Math.round(40/4)), baseAttack: Math.max(1, Math.round(8/4)), baseDefense: Math.max(1, Math.round(10/2)), goldDrop: [Math.max(1, Math.round(9/4)), Math.max(1, Math.round(20/4))] as [number,number], xpDrop: Math.max(1, Math.round(30/4)), color: 'bg-slate-400', sizeClass: 'w-12 h-12' },
  { id: 'flame_lizard', name: '화염 도마뱀', baseHp: Math.max(1, Math.round(55/4)), baseAttack: Math.max(1, Math.round(10/4)), baseDefense: Math.max(1, Math.round(3/2)), goldDrop: [Math.max(1, Math.round(11/4)), Math.max(1, Math.round(23/4))] as [number,number], xpDrop: Math.max(1, Math.round(38/4)), color: 'bg-red-500', sizeClass: 'w-13 h-9' },
  { id: 'crystal_wisp', name: '수정 소환수', baseHp: Math.max(1, Math.round(25/4)), baseAttack: Math.max(1, Math.round(15/4)), baseDefense: Math.max(0, Math.round(0/2)), goldDrop: [Math.max(1, Math.round(15/4)), Math.max(1, Math.round(30/4))] as [number,number], xpDrop: Math.max(1, Math.round(45/4)), color: 'bg-fuchsia-500', sizeClass: 'w-8 h-8' },
  { id: 'forest_sprite', name: '숲의 정령', baseHp: Math.max(1, Math.round(30/4)), baseAttack: Math.max(1, Math.round(6/4)), baseDefense: Math.max(1, Math.round(2/2)), goldDrop: [Math.max(1, Math.round(6/4)), Math.max(1, Math.round(12/4))] as [number,number], xpDrop: Math.max(1, Math.round(20/4)), color: 'bg-green-500', sizeClass: 'w-9 h-9' },
];

export const SKILL_DEFINITIONS: SkillDefinition[] = [
  // ========== 전투 트리 (Combat Tree) ==========
  {
    id: 'strength_boost', 
    name: '단련된 전투광',
    description: (level: number) => `공격력이 ${level * 5}% 증가합니다.`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: (level: number) => [{ stat: 'attack', value: level * 0.05, type: 'percent' } as StatModifier],
    icon: '💪',
    prerequisites: [],
  },
  {
    id: 'power_strike', 
    name: '강타',
    description: (level: number) => `공격 시 ${level * 6 + 4}% 확률로 다음 공격에 ${level * 10}의 추가 물리 피해를 입힙니다. (엔진 로직)`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: () => [], 
    icon: '⚔️',
    prerequisites: ['strength_boost'],
  },
  {
    id: 'executioner_strike', 
    name: '처형자의 일격',
    description: (level: number) => `체력이 30% 이하인 대상에게 ${level * 10 + 5}%의 추가 피해를 입힙니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '☠️',
    prerequisites: ['power_strike'],
  },
  {
    id: 'battle_trance',
    name: '전투 무아지경',
    description: (level: number) => `몬스터 처치 시 ${level * 2}초 동안 공격 속도가 ${level * 5}%, 이동 속도가 ${level * 3}% 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🌀',
    prerequisites: ['executioner_strike'],
  },
  {
    id: 'sunder_armor',
    name: '방어구 가르기',
    description: (level: number) => `공격 시 ${level * 8 + 7}% 확률로 ${level + 2}초 동안 대상의 방어력을 ${level * 5 + 10}% 감소시킵니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🛡️‍💥',
    prerequisites: ['power_strike'],
  },
  {
    id: 'shattering_blows',
    name: '파쇄격',
    description: (level: number) => `방어력이 감소된 대상에게 ${level * 15 + 5}%의 추가 피해를 입힙니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🔨',
    prerequisites: ['sunder_armor'],
  },
  {
    id: 'weapon_focus',
    name: '무기 숙련',
    description: (level: number) => `공격력이 ${level * 2}만큼 증가합니다.`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: (level: number) => [{ stat: 'attack', value: level * 2, type: 'flat' } as StatModifier],
    icon: '🗡️',
    prerequisites: ['strength_boost'],
  },
  {
    id: 'enhanced_strikes',
    name: '강화된 일격',
    description: (level: number) => `공격력이 추가로 ${level * 3}% 증가합니다.`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: (level: number) => [{ stat: 'attack', value: level * 0.03, type: 'percent' } as StatModifier],
    icon: '✨⚔️',
    prerequisites: ['weapon_focus'],
  },
  {
    id: 'combat_flow',
    name: '전투의 흐름',
    description: (level: number) => `3회 연속 공격 시 ${level * 2}초 동안 공격 속도가 ${level * 10}% 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '💨',
    prerequisites: ['enhanced_strikes'],
  },
  {
    id: 'heavy_blows',
    name: '묵직한 강타',
    description: (level: number) => `공격력이 ${level * 8}% 증가하지만, 공격 속도가 ${level * 3}% 감소합니다.`, 
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: (level: number) => [
        { stat: 'attack', value: level * 0.08, type: 'percent' },
        { stat: 'attackSpeed', value: -(level * 0.03), type: 'percent' } 
    ] as StatModifier[], 
    icon: '🏋️',
    prerequisites: [],
  },
  {
    id: 'crushing_impact',
    name: '분쇄 충격',
    description: (level: number) => `공격 시 ${level * 5 + 5}% 확률로 대상을 ${level * 0.5 + 0.5}초 동안 기절시킵니다. (보스에게는 효과 감소, 엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🧱',
    prerequisites: ['heavy_blows'],
  },
  {
    id: 'unstoppable_force',
    name: '멈출 수 없는 힘',
    description: (level: number) => `기절시킨 대상에게 다음 ${level}번의 공격이 치명타로 적중할 확률이 ${level * 10 + 5}% 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🚂',
    prerequisites: ['crushing_impact'],
  },
  {
    id: 'quake_stomp',
    name: '지진 발구르기',
    description: (level: number) => `주 대상 공격 시 주변 적들에게 공격력의 ${level * 10 + 5}% 피해를 주고 ${level + 1}초 동안 이동 속도를 20% 감소시킵니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 3,
    effects: () => [], 
    icon: '🦶💥',
    prerequisites: ['unstoppable_force'],
  },

  // ========== 생존 트리 (Survival Tree) ==========
  {
    id: 'vitality_boost', 
    name: '강인함',
    description: (level: number) => `최대 체력이 ${level * 10}% 증가합니다.`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: (level: number) => [{ stat: 'maxHp', value: level * 0.10, type: 'percent' } as StatModifier],
    icon: '❤️',
    prerequisites: [],
  },
  {
    id: 'health_regen_boost', 
    name: '빠른 회복',
    description: (level: number) => `초당 체력 재생량이 ${level * 0.5} 증가합니다.`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: (level: number) => [{ stat: 'healthRegen', value: level * 0.5, type: 'flat' } as StatModifier],
    icon: '✨',
    prerequisites: ['vitality_boost'],
  },
  {
    id: 'bulwark', 
    name: '보루',
    description: (level: number) => `방어력이 ${level * 3}만큼 영구적으로 증가합니다.`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: (level: number) => [{ stat: 'defense', value: level * 3, type: 'flat' } as StatModifier],
    icon: '🛡️',
    prerequisites: ['health_regen_boost'],
  },
  {
    id: 'resilience',
    name: '회복탄력성',
    description: (level: number) => `받는 모든 피해가 ${level * 1 + 1}만큼 감소합니다. (최소 피해량 1 적용 후, 엔진 로직)`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '💪❤️',
    prerequisites: ['bulwark'],
  },
  {
    id: 'nimble_defense',
    name: '날렵한 방어',
    description: (level: number) => `${level * 3 + 2}% 확률로 공격을 회피하여 받는 피해를 50% 줄입니다. (엔진 로직)`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🤸',
    prerequisites: ['health_regen_boost'],
  },
  {
    id: 'evasive_maneuvers',
    name: '회피 기동',
    description: (level: number) => `회피 성공 시 ${level + 1}초 동안 이동 속도가 ${level * 10 + 10}% 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: () => [], 
    icon: '🏃💨',
    prerequisites: ['nimble_defense'],
  },
  {
    id: 'iron_will',
    name: '강철 의지',
    description: (level: number) => `자신에게 적용되는 모든 해로운 상태 효과의 지속 시간이 ${level * 6 + 4}% 감소합니다. (엔진 로직)`,
    maxLevel: 4,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: () => [], 
    icon: '🧠💪',
    prerequisites: ['vitality_boost'],
  },
  {
    id: 'purification',
    name: '정화',
    description: (level: number) => `해로운 상태 효과에 걸릴 확률이 ${level * 5 + 5}% 감소합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '💧',
    prerequisites: ['iron_will'],
  },
  {
    id: 'unyielding_spirit',
    name: '불굴의 정신',
    description: (level: number) => `체력이 30% 이하일 때 받는 모든 치유 효과가 ${level * 10 + 10}% 증폭됩니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '💖✨',
    prerequisites: ['purification'],
  },
  {
    id: 'thick_hide',
    name: '두꺼운 가죽',
    description: (level: number) => `방어력이 ${level * 4}% 증가합니다.`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: (level: number) => [{ stat: 'defense', value: level * 0.04, type: 'percent' } as StatModifier],
    icon: '🐗',
    prerequisites: [],
  },
  {
    id: 'thorns_aura',
    name: '가시 갑옷',
    description: (level: number) => `공격을 받을 때마다 공격자에게 (자신의 방어력의 ${level * 5 + 5}%)만큼의 물리 피해를 반사합니다. (엔진 로직)`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: () => [], 
    icon: '🌵',
    prerequisites: ['thick_hide'],
  },
  {
    id: 'spiked_armor',
    name: '날카로운 갑옷',
    description: (level: number) => `가시 갑옷의 반사 피해량이 ${level * 10 + 5}% 증가하고, ${level * 5 + 5}% 확률로 공격자에게 3초간 출혈을 겁니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🦔',
    prerequisites: ['thorns_aura'],
  },
  {
    id: 'retribution',
    name: '응징',
    description: (level: number) => `자신이 치명타 공격을 받으면, 다음 ${level}번의 공격의 피해량이 ${level * 10 + 10}% 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '⚖️',
    prerequisites: ['spiked_armor'],
  },

  // ========== 정밀 트리 (Precision Tree) ==========
  {
    id: 'crit_chance_boost', 
    name: '날카로운 눈',
    description: (level: number) => `치명타 확률이 ${level * 2}% 증가합니다.`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: (level: number) => [{ stat: 'critChance', value: level * 0.02, type: 'flat' } as StatModifier], 
    icon: '🎯',
    prerequisites: [],
  },
  {
    id: 'crit_damage_boost', 
    name: '치명적인 일격',
    description: (level: number) => `치명타 피해량이 ${level * 10}% 증가합니다.`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: (level: number) => [{ stat: 'critDamage', value: level * 0.10, type: 'flat' } as StatModifier],
    icon: '💥',
    prerequisites: ['crit_chance_boost'],
  },
  {
    id: 'precision_mastery', 
    name: '정밀함의 대가',
    description: (level: number) => `치명타 확률이 ${level * 1}% 추가로 증가하고, 치명타 피해량이 ${level * 5}% 추가로 증가합니다.`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: (level: number) => [
        { stat: 'critChance', value: level * 0.01, type: 'flat' },
        { stat: 'critDamage', value: level * 0.05, type: 'flat' }
    ] as StatModifier[],
    icon: '👁️',
    prerequisites: ['crit_damage_boost'],
  },
  {
    id: 'lethal_tempo',
    name: '치명적 속도',
    description: (level: number) => `치명타 발생 시 ${level + 1}초 동안 공격 속도가 ${level * 5 + 5}% 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '⏱️',
    prerequisites: ['precision_mastery'],
  },
  {
    id: 'piercing_crits',
    name: '꿰뚫는 치명타',
    description: (level: number) => `치명타 공격이 대상 방어력의 ${level * 6 + 4}%를 무시합니다. (엔진 로직)`,
    maxLevel: 4,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '📌',
    prerequisites: ['crit_damage_boost'],
  },
  {
    id: 'expose_weakness',
    name: '약점 노출',
    description: (level: number) => `치명타 공격 시 ${level * 10 + 5}% 확률로 대상이 5초간 받는 모든 피해를 ${level * 3 + 2}% 증가시키는 약점을 노출합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🔍',
    prerequisites: ['piercing_crits'],
  },
  {
    id: 'finishing_touch',
    name: '마무리 일격',
    description: (level: number) => `체력이 25% 이하인 대상에게 치명타 확률이 ${level * 5 + 5}% 추가로 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: () => [], 
    icon: '🔪',
    prerequisites: ['crit_chance_boost'],
  },
  {
    id: 'hunter_instinct',
    name: '사냥꾼의 본능',
    description: (level: number) => `보스 몬스터에게 주는 모든 피해가 ${level * 5 + 2}% 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🐺',
    prerequisites: ['finishing_touch'],
  },
  {
    id: 'master_tactician',
    name: '전술의 대가',
    description: (level: number) => `전투 시작 후 첫 ${level * 3 + 2}초 동안 치명타 확률이 20%, 치명타 피해량이 30% 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🗺️',
    prerequisites: ['hunter_instinct'],
  },
  {
    id: 'keen_senses',
    name: '예리한 감각',
    description: (level: number) => `골드 발견량이 ${level * 7 + 3}% 증가합니다. (엔진 로직)`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: () => [], 
    icon: '💰👀',
    prerequisites: [],
  },
  {
    id: 'treasure_hunter',
    name: '보물 사냥꾼',
    description: (level: number) => `골드 발견량이 추가로 ${level * 10}% 증가합니다. (엔진 로직)`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: () => [], 
    icon: '🪙✨',
    prerequisites: ['keen_senses'],
  },
  {
    id: 'fortune_favors',
    name: '행운의 가호',
    description: (level: number) => `몬스터 처치 시 ${level * 1 + 1}% 확률로 소량의 추가 골드를 즉시 획득합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🍀',
    prerequisites: ['treasure_hunter'],
  },
  {
    id: 'lucky_streak',
    name: '행운 연쇄',
    description: (level: number) => `5초 안에 연속으로 몬스터 3마리 처치 시 ${level * 30 + 30}초 동안 골드 발견량이 50% 증가합니다. (최대 1회 중첩, 엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '🎰',
    prerequisites: ['fortune_favors'],
  },
  {
    id: 'insightful_strikes',
    name: '통찰력 있는 공격',
    description: (level: number) => `공격 시 ${level * 3 + 2}% 확률로 ${level * 2 + 1}초 동안 자신의 공격력이 ${level * 5 + 3}% 증가합니다. (엔진 로직)`,
    maxLevel: 5,
    cost: (currentLevel: number) => (currentLevel + 1) * 1,
    effects: () => [], 
    icon: '💡',
    prerequisites: ['keen_senses'], 
  },
  {
    id: 'tactical_advantage',
    name: '전술적 우위',
    description: (level: number) => `통찰력 있는 공격 발동 시 추가로 ${level * 2}초 동안 모든 주요 능력치(공격력, 방어력, 최대 체력)가 ${level * 2 + 1}% 증가합니다. (엔진 로직)`,
    maxLevel: 3,
    cost: (currentLevel: number) => (currentLevel + 1) * 2,
    effects: () => [], 
    icon: '📈',
    prerequisites: ['insightful_strikes'],
  }
];

type ItemBaseDefinition = Array<{
  name: string;
  baseModifiers: Array<{
    stat: keyof PlayerStats | 'critChance' | 'critDamage' | 'healthRegen' | 'attackSpeed' | 'movementSpeed';
    value: number;
    type: 'flat' | 'percent';
  }>;
  icon: string;
  enhancementLevel: 0; // All base items start at +0
}>;

export const ITEM_BASES: Record<ItemType, ItemBaseDefinition> = {
  [ItemType.WEAPON]: [
    // Swords
    { name: "녹슨 검", baseModifiers: [{ stat: 'attack', value: 3, type: 'flat' }], icon: "⚔️", enhancementLevel: 0 },
    { name: "낡은 단검", baseModifiers: [{ stat: 'attack', value: 2, type: 'flat' }, { stat: 'attackSpeed', value: 0.02, type: 'flat' }], icon: "🗡️", enhancementLevel: 0 },
    { name: "보병용 검", baseModifiers: [{ stat: 'attack', value: 4, type: 'flat' }], icon: "⚔️", enhancementLevel: 0 },
    { name: "전투용 도끼", baseModifiers: [{ stat: 'attack', value: 5, type: 'flat' }], icon: "🪓", enhancementLevel: 0 },
    { name: "사냥꾼 활", baseModifiers: [{ stat: 'attack', value: 3, type: 'flat' }, { stat: 'critChance', value: 0.01, type: 'flat' }], icon: "🏹", enhancementLevel: 0 },
    { name: "견습생 지팡이", baseModifiers: [{ stat: 'attack', value: 2, type: 'flat' }, { stat: 'maxHp', value: 5, type: 'flat' }], icon: "🪄", enhancementLevel: 0 },
    { name: "무거운 몽둥이", baseModifiers: [{ stat: 'attack', value: 6, type: 'flat' }, { stat: 'attackSpeed', value: -0.05, type: 'flat' }], icon: "몽둥이", enhancementLevel: 0 },
    { name: "투척용 창", baseModifiers: [{ stat: 'attack', value: 4, type: 'flat' }, { stat: 'critDamage', value: 0.05, type: 'flat' }], icon: "矛", enhancementLevel: 0 },
    { name: "날카로운 레이피어", baseModifiers: [{ stat: 'attack', value: 3, type: 'flat' }, { stat: 'attackSpeed', value: 0.03, type: 'flat' }], icon: "🤺", enhancementLevel: 0 },
    { name: "양손 대검", baseModifiers: [{ stat: 'attack', value: 7, type: 'flat' }, { stat: 'attackSpeed', value: -0.08, type: 'flat' }], icon: "🗿🗡️", enhancementLevel: 0 },
    { name: "전쟁 망치", baseModifiers: [{ stat: 'attack', value: 6, type: 'flat' }, { stat: 'critDamage', value: 0.1, type: 'flat' }], icon: "🔨", enhancementLevel: 0 },
    { name: "마법 단검", baseModifiers: [{ stat: 'attack', value: 2, type: 'flat' }, { stat: 'healthRegen', value: 0.1, type: 'flat' }], icon: "🔮🗡️", enhancementLevel: 0 },
    { name: "강철 검", baseModifiers: [{ stat: 'attack', value: 5, type: 'flat' }], icon: "⚔️", enhancementLevel: 0 },
    { name: "오크족 도끼", baseModifiers: [{ stat: 'attack', value: 6, type: 'flat' }], icon: "🪓", enhancementLevel: 0 },
    { name: "엘프 활", baseModifiers: [{ stat: 'attack', value: 4, type: 'flat' }, { stat: 'critChance', value: 0.02, type: 'flat' }], icon: "🏹", enhancementLevel: 0 },
    { name: "현자의 지팡이", baseModifiers: [{ stat: 'attack', value: 3, type: 'flat' }, { stat: 'maxHp', value: 10, type: 'flat' }], icon: "🪄", enhancementLevel: 0 },
    { name: "강철 몽둥이", baseModifiers: [{ stat: 'attack', value: 7, type: 'flat' }, { stat: 'attackSpeed', value: -0.06, type: 'flat' }], icon: "몽둥이", enhancementLevel: 0 },
    { name: "기사의 창", baseModifiers: [{ stat: 'attack', value: 5, type: 'flat' }, { stat: 'critDamage', value: 0.08, type: 'flat' }], icon: "矛", enhancementLevel: 0 },
    { name: "결투용 레이피어", baseModifiers: [{ stat: 'attack', value: 4, type: 'flat' }, { stat: 'attackSpeed', value: 0.04, type: 'flat' }], icon: "🤺", enhancementLevel: 0 },
    { name: "룬 대검", baseModifiers: [{ stat: 'attack', value: 8, type: 'flat' }, { stat: 'attackSpeed', value: -0.1, type: 'flat' }], icon: "🗿🗡️", enhancementLevel: 0 },
  ],
  [ItemType.ARMOR_CHEST]: [
    { name: "천 조끼", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }], icon: "🥋", enhancementLevel: 0 },
    { name: "가죽 조끼", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }], icon: "👕", enhancementLevel: 0 },
    { name: "사슬 갑옷", baseModifiers: [{ stat: 'defense', value: 4, type: 'flat' }], icon: "🛡️", enhancementLevel: 0 },
    { name: "판금 갑옷", baseModifiers: [{ stat: 'defense', value: 6, type: 'flat' }], icon: "🎽", enhancementLevel: 0 },
    { name: "누비 갑옷", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }, { stat: 'maxHp', value: 3, type: 'flat' }], icon: "🧥", enhancementLevel: 0 },
    { name: "스터드 가죽 갑옷", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }], icon: "👕", enhancementLevel: 0 },
    { name: "미늘 갑옷", baseModifiers: [{ stat: 'defense', value: 5, type: 'flat' }], icon: "🛡️", enhancementLevel: 0 },
    { name: "강철 판금 갑옷", baseModifiers: [{ stat: 'defense', value: 7, type: 'flat' }], icon: "🎽", enhancementLevel: 0 },
    { name: "마법사 로브", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'healthRegen', value: 0.1, type: 'flat' }], icon: "👘", enhancementLevel: 0 },
    { name: "도적의 조끼", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }, { stat: 'movementSpeed', value: 0.05, type: 'flat' }], icon: "🧥", enhancementLevel: 0 },
    { name: "용병 갑옷", baseModifiers: [{ stat: 'defense', value: 4, type: 'flat' }, { stat: 'maxHp', value: 5, type: 'flat' }], icon: "🛡️", enhancementLevel: 0 },
    { name: "기사의 갑옷", baseModifiers: [{ stat: 'defense', value: 8, type: 'flat' }], icon: "🎽", enhancementLevel: 0 },
    { name: "모험가의 튜닉", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }], icon: "🥋", enhancementLevel: 0 },
    { name: "사냥꾼의 가죽옷", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }], icon: "👕", enhancementLevel: 0 },
    { name: "전사의 사슬갑옷", baseModifiers: [{ stat: 'defense', value: 5, type: 'flat' }], icon: "🛡️", enhancementLevel: 0 },
    { name: "군주의 판금갑옷", baseModifiers: [{ stat: 'defense', value: 9, type: 'flat' }], icon: "🎽", enhancementLevel: 0 },
    { name: "여행자 망토", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'maxHp', value: 2, type: 'flat' }], icon: "🧥", enhancementLevel: 0 },
    { name: "경화 가죽 갑옷", baseModifiers: [{ stat: 'defense', value: 4, type: 'flat' }], icon: "👕", enhancementLevel: 0 },
    { name: "정예 미늘 갑옷", baseModifiers: [{ stat: 'defense', value: 6, type: 'flat' }], icon: "🛡️", enhancementLevel: 0 },
    { name: "수호자의 판금 갑옷", baseModifiers: [{ stat: 'defense', value: 10, type: 'flat' }], icon: "🎽", enhancementLevel: 0 },
  ],
  [ItemType.ARMOR_HEAD]: [
    { name: "천 후드", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }], icon: "🧢", enhancementLevel: 0 },
    { name: "가죽 투구", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }], icon: "🎓", enhancementLevel: 0 },
    { name: "철제 투구", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }], icon: "⛑️", enhancementLevel: 0 },
    { name: "강철 투구", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }], icon: "🎩", enhancementLevel: 0 },
    { name: "마법사 모자", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'maxHp', value: 2, type: 'flat' }], icon: "👒", enhancementLevel: 0 },
    { name: "사냥꾼 두건", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'critChance', value: 0.005, type: 'flat' }], icon: "🧢", enhancementLevel: 0 },
    { name: "전사 투구", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }, { stat: 'maxHp', value: 3, type: 'flat' }], icon: "🎓", enhancementLevel: 0 },
    { name: "기사 투구", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }, { stat: 'defense', value: 1, type: 'flat' }], icon: "⛑️", enhancementLevel: 0 },
    { name: "지혜의 서클릿", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'healthRegen', value: 0.1, type: 'flat' }], icon: "👑", enhancementLevel: 0 },
    { name: "수호자 얼굴보호대", baseModifiers: [{ stat: 'defense', value: 4, type: 'flat' }], icon: "🎩", enhancementLevel: 0 },
  ],
  [ItemType.ARMOR_LEGS]: [
    { name: "천 바지", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
    { name: "가죽 바지", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
    { name: "사슬 레깅스", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
    { name: "판금 각반", baseModifiers: [{ stat: 'defense', value: 4, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
    { name: "누비 바지", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'maxHp', value: 2, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
    { name: "스터드 가죽 바지", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }, { stat: 'movementSpeed', value: 0.02, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
    { name: "미늘 레깅스", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }, { stat: 'maxHp', value: 3, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
    { name: "강철 각반", baseModifiers: [{ stat: 'defense', value: 5, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
    { name: "마법사 바지", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'healthRegen', value: 0.05, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
    { name: "도적의 바지", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }, { stat: 'critChance', value: 0.002, type: 'flat' }], icon: "👖", enhancementLevel: 0 },
  ],
  [ItemType.ARMOR_FEET]: [
    { name: "낡은 신발", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'movementSpeed', value: 0.1, type: 'flat' }], icon: "👟", enhancementLevel: 0 },
    { name: "가죽 장화", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'movementSpeed', value: 0.12, type: 'flat' }], icon: "👢", enhancementLevel: 0 },
    { name: "사슬 장화", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }, { stat: 'movementSpeed', value: 0.08, type: 'flat' }], icon: "👞", enhancementLevel: 0 },
    { name: "판금 장화", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }, { stat: 'movementSpeed', value: 0.05, type: 'flat' }], icon: "🥾", enhancementLevel: 0 },
    { name: "가벼운 샌들", baseModifiers: [{ stat: 'defense', value: 0, type: 'flat' }, { stat: 'movementSpeed', value: 0.15, type: 'flat' }], icon: "🩴", enhancementLevel: 0 },
    { name: "여행자 신발", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'movementSpeed', value: 0.13, type: 'flat' }], icon: "👟", enhancementLevel: 0 },
    { name: "전투 장화", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }, { stat: 'movementSpeed', value: 0.1, type: 'flat' }], icon: "👢", enhancementLevel: 0 },
    { name: "기사의 그리브", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }, { stat: 'movementSpeed', value: 0.06, type: 'flat' }], icon: "🥾", enhancementLevel: 0 },
    { name: "신속의 장화", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }, { stat: 'movementSpeed', value: 0.18, type: 'flat' }], icon: "🏃👟", enhancementLevel: 0 },
    { name: "무거운 철제 장화", baseModifiers: [{ stat: 'defense', value: 4, type: 'flat' }, { stat: 'movementSpeed', value: 0.03, type: 'flat' }], icon: "⚓👢", enhancementLevel: 0 },
  ],
  [ItemType.ARMOR_HANDS]: [
    { name: "천 장갑", baseModifiers: [{ stat: 'attackSpeed', value: 0.05, type: 'flat' }], icon: "🧤", enhancementLevel: 0 },
    { name: "가죽 장갑", baseModifiers: [{ stat: 'attackSpeed', value: 0.03, type: 'flat' }, { stat: 'defense', value: 1, type: 'flat' }], icon: "🥊", enhancementLevel: 0 },
    { name: "사슬 장갑", baseModifiers: [{ stat: 'attackSpeed', value: 0.02, type: 'flat' }, { stat: 'defense', value: 2, type: 'flat' }], icon: "🛠️🧤", enhancementLevel: 0 },
    { name: "판금 건틀릿", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }], icon: "🦾", enhancementLevel: 0 },
    { name: "작업용 장갑", baseModifiers: [{ stat: 'attackSpeed', value: 0.06, type: 'flat' }], icon: "🧤", enhancementLevel: 0 },
    { name: "전투용 장갑", baseModifiers: [{ stat: 'attackSpeed', value: 0.04, type: 'flat' }, { stat: 'defense', value: 1, type: 'flat' }, { stat: 'attack', value: 1, type: 'flat' }], icon: "🥊", enhancementLevel: 0 },
    { name: "미늘 장갑", baseModifiers: [{ stat: 'attackSpeed', value: 0.02, type: 'flat' }, { stat: 'defense', value: 2, type: 'flat' }, { stat: 'maxHp', value: 2, type: 'flat' }], icon: "🛠️🧤", enhancementLevel: 0 },
    { name: "기사의 건틀릿", baseModifiers: [{ stat: 'defense', value: 4, type: 'flat' }], icon: "🦾", enhancementLevel: 0 },
    { name: "명사수 장갑", baseModifiers: [{ stat: 'attackSpeed', value: 0.07, type: 'flat' }, { stat: 'critChance', value: 0.005, type: 'flat' }], icon: "🎯🧤", enhancementLevel: 0 },
    { name: "무거운 철제 건틀릿", baseModifiers: [{ stat: 'defense', value: 3, type: 'flat' }, { stat: 'attack', value: 2, type: 'flat' }, { stat: 'attackSpeed', value: -0.02, type: 'flat' }], icon: "⚓🦾", enhancementLevel: 0 },
  ],
  [ItemType.RING]: [
    { name: "구리 반지", baseModifiers: [{ stat: 'maxHp', value: 10, type: 'flat' }], icon: "💍", enhancementLevel: 0 },
    { name: "은 반지", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }], icon: "💍", enhancementLevel: 0 },
    { name: "금 반지", baseModifiers: [{ stat: 'healthRegen', value: 0.1, type: 'flat' }], icon: "🪙", enhancementLevel: 0 },
    { name: "백금 반지", baseModifiers: [{ stat: 'attack', value: 1, type: 'flat' }], icon: "💎", enhancementLevel: 0 },
    { name: "자수정 반지", baseModifiers: [{ stat: 'maxHp', value: 12, type: 'flat' }], icon: "💜💍", enhancementLevel: 0 },
    { name: "루비 반지", baseModifiers: [{ stat: 'attack', value: 2, type: 'flat' }], icon: "❤️‍🔥💍", enhancementLevel: 0 },
    { name: "사파이어 반지", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }], icon: "💙💍", enhancementLevel: 0 },
    { name: "에메랄드 반지", baseModifiers: [{ stat: 'healthRegen', value: 0.2, type: 'flat' }], icon: "💚💍", enhancementLevel: 0 },
    { name: "해골 반지", baseModifiers: [{ stat: 'critChance', value: 0.005, type: 'flat' }], icon: "💀💍", enhancementLevel: 0 },
    { name: "룬 문자 반지", baseModifiers: [{ stat: 'critDamage', value: 0.03, type: 'flat' }], icon: "📜💍", enhancementLevel: 0 },
  ],
  [ItemType.AMULET]: [
    { name: "조잡한 목걸이", baseModifiers: [{ stat: 'healthRegen', value: 0.2, type: 'flat' }], icon: "💎", enhancementLevel: 0 },
    { name: "청동 펜던트", baseModifiers: [{ stat: 'maxHp', value: 8, type: 'flat' }], icon: "🥉", enhancementLevel: 0 },
    { name: "은제 로켓", baseModifiers: [{ stat: 'defense', value: 1, type: 'flat' }], icon: "🥈", enhancementLevel: 0 },
    { name: "금제 체인", baseModifiers: [{ stat: 'attack', value: 1, type: 'flat' }], icon: "🥇", enhancementLevel: 0 },
    { name: "토파즈 목걸이", baseModifiers: [{ stat: 'healthRegen', value: 0.25, type: 'flat' }], icon: "💛💎", enhancementLevel: 0 },
    { name: "가넷 부적", baseModifiers: [{ stat: 'maxHp', value: 15, type: 'flat' }], icon: "❤️‍🩹💎", enhancementLevel: 0 },
    { name: "오팔 아뮬렛", baseModifiers: [{ stat: 'defense', value: 2, type: 'flat' }], icon: "🤍💎", enhancementLevel: 0 },
    { name: "흑요석 탈리스만", baseModifiers: [{ stat: 'attack', value: 2, type: 'flat' }], icon: "🖤💎", enhancementLevel: 0 },
    { name: "부족 부적", baseModifiers: [{ stat: 'critDamage', value: 0.05, type: 'flat' }], icon: "🗿💎", enhancementLevel: 0 },
    { name: "성스러운 상징", baseModifiers: [{ stat: 'attackSpeed', value: 0.01, type: 'flat' }], icon: "✝️💎", enhancementLevel: 0 },
  ]
};

export const MAX_BATTLE_LOG_MESSAGES = 35; 
export const PLAYER_ID = 'player';
export const INVENTORY_SLOTS = 20;
export const MAX_ATTACK_EVENTS = 10; 
export const MAX_SKILL_PROC_EVENTS = 15; 

export const SLOT_ICON_MAP: Record<string, string> = {
  [ItemType.WEAPON]: '⚔️',
  [ItemType.ARMOR_HEAD]: '👑',
  [ItemType.ARMOR_CHEST]: '👕',
  [ItemType.ARMOR_LEGS]: '👖',
  [ItemType.ARMOR_FEET]: '👟',
  [ItemType.ARMOR_HANDS]: '🧤',
  [ItemType.RING]: '💍',
  [ItemType.AMULET]: '💎',
  ['ENHANCEMENT_PANEL_ICON']: '🔨', // Icon for the enhancement panel button
};

export const TAILWIND_COLOR_MAP_ADDITIONS: Record<string, string> = {
  'bg-emerald-700': '#047857',
  'bg-lime-600': '#65a30d',
  'bg-cyan-600': '#0891b2',
  'bg-stone-500': '#78716c',
  'bg-indigo-700': '#4338ca',
  'bg-amber-700': '#b45309',
  'bg-teal-700': '#0f766e',
  'bg-orange-600': '#ea580c',
  'bg-sky-700': '#0369a1',
  'bg-neutral-600': '#525252',
  'bg-rose-700': '#be123c',
  'bg-slate-400': '#94a3b8',
  'bg-red-500': '#ef4444',
  'bg-fuchsia-500': '#d946ef',
  'bg-green-500': '#22c55e',
};


export const SHOP_NUM_ITEMS_TO_DISPLAY = 8;
export const SELL_PRICE_MODIFIER = 0.5; 
export const SHOP_ITEM_LEVEL_SCALING_FACTOR = 0.8; 
export const SHOP_REFRESH_COST = 50;